# 应用配置
spring:
  application:
    name: consultantRAG

# LangChain4j 标准配置前缀 (必须是 langchain4j.ollama...)
langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: qwen3:4b  # 确保本地 ollama list 里有这个名字
      timeout: PT60S        # 注意：部分版本要求 ISO-8601 格式，PT60S 代表 60 秒
      temperature: 0.7
      top-p: 1.0